/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastros;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author m132175
 */
public class NewJFrame extends javax.swing.JFrame {
    
    ArrayList<Usuario> listaUsers = new ArrayList<>();
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        
        addCad.setVisible(false);
        attCad.setVisible(false);
        buscaCad.setVisible(false);
        excCad.setVisible(false);
        container.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        addCad = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addNomeVar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addIdadeVar = new javax.swing.JTextField();
        addCidVar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AddUserBtn = new javax.swing.JButton();
        buscaCad = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        excCad = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        excIdVar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        excNomeVar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        excIdadeVar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        excCidVar = new javax.swing.JTextField();
        excExcluirBtn = new javax.swing.JButton();
        attCad = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        attIdVar = new javax.swing.JTextField();
        attNomeVar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        attIdadeVar = new javax.swing.JTextField();
        attCidVar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        attCadBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Adicionar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jButton6.setText("Atualizar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jButton7.setText("Excluir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        container.setLayout(new java.awt.CardLayout());

        addCad.setBackground(new java.awt.Color(255, 102, 51));
        addCad.setLayout(null);

        jLabel1.setText("Adicionando Cadastro");
        addCad.add(jLabel1);
        jLabel1.setBounds(57, 25, 118, 16);

        jLabel2.setText("Nome");
        addCad.add(jLabel2);
        jLabel2.setBounds(19, 62, 33, 16);
        addCad.add(addNomeVar);
        addNomeVar.setBounds(70, 60, 155, 22);

        jLabel3.setText("Idade:");
        addCad.add(jLabel3);
        jLabel3.setBounds(20, 90, 32, 16);
        addCad.add(addIdadeVar);
        addIdadeVar.setBounds(70, 90, 155, 22);
        addCad.add(addCidVar);
        addCidVar.setBounds(70, 120, 155, 22);

        jLabel4.setText("Cidade");
        addCad.add(jLabel4);
        jLabel4.setBounds(20, 120, 37, 16);

        AddUserBtn.setText("Adicionar");
        AddUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserBtnActionPerformed(evt);
            }
        });
        addCad.add(AddUserBtn);
        AddUserBtn.setBounds(140, 160, 81, 23);

        container.add(addCad, "card2");

        buscaCad.setBackground(new java.awt.Color(255, 102, 51));
        buscaCad.setLayout(null);

        jLabel15.setText("Nome:");
        buscaCad.add(jLabel15);
        jLabel15.setBounds(26, 34, 36, 16);
        buscaCad.add(jTextField12);
        jTextField12.setBounds(68, 31, 250, 22);

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        buscaCad.add(jButton4);
        jButton4.setBounds(330, 30, 72, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Idade", "Cidade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buscaCad.add(jScrollPane1);
        jScrollPane1.setBounds(26, 65, 370, 280);

        container.add(buscaCad, "card3");

        excCad.setBackground(new java.awt.Color(255, 102, 51));
        excCad.setLayout(null);

        jLabel10.setText("Excluindo Cadastro");
        excCad.add(jLabel10);
        jLabel10.setBounds(59, 22, 102, 16);

        jLabel11.setText("Id:");
        excCad.add(jLabel11);
        jLabel11.setBounds(28, 59, 13, 16);
        excCad.add(excIdVar);
        excIdVar.setBounds(88, 56, 64, 22);

        jLabel12.setText("Nome:");
        excCad.add(jLabel12);
        jLabel12.setBounds(28, 93, 36, 16);
        excCad.add(excNomeVar);
        excNomeVar.setBounds(88, 90, 153, 22);

        jLabel13.setText("Idade:");
        excCad.add(jLabel13);
        jLabel13.setBounds(28, 127, 32, 16);
        excCad.add(excIdadeVar);
        excIdadeVar.setBounds(86, 124, 155, 22);

        jLabel14.setText("Cidade:");
        excCad.add(jLabel14);
        jLabel14.setBounds(28, 161, 40, 16);
        excCad.add(excCidVar);
        excCidVar.setBounds(86, 158, 155, 22);

        excExcluirBtn.setText("Excluir");
        excExcluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excExcluirBtnActionPerformed(evt);
            }
        });
        excCad.add(excExcluirBtn);
        excExcluirBtn.setBounds(169, 192, 72, 23);

        container.add(excCad, "card4");

        attCad.setBackground(new java.awt.Color(255, 102, 51));
        attCad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        attCad.setLayout(null);

        jLabel5.setText("Atualizado Cadastro");
        attCad.add(jLabel5);
        jLabel5.setBounds(67, 30, 106, 16);

        jLabel6.setText("ID:");
        attCad.add(jLabel6);
        jLabel6.setBounds(23, 61, 14, 16);

        attIdVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attIdVarActionPerformed(evt);
            }
        });
        attCad.add(attIdVar);
        attIdVar.setBounds(83, 58, 64, 22);
        attCad.add(attNomeVar);
        attNomeVar.setBounds(83, 92, 159, 22);

        jLabel7.setText("Nome:");
        attCad.add(jLabel7);
        jLabel7.setBounds(23, 95, 36, 16);

        jLabel8.setText("Idade:");
        attCad.add(jLabel8);
        jLabel8.setBounds(23, 129, 32, 16);

        attIdadeVar.setToolTipText("");
        attCad.add(attIdadeVar);
        attIdadeVar.setBounds(81, 126, 161, 22);
        attCad.add(attCidVar);
        attCidVar.setBounds(81, 160, 161, 22);

        jLabel9.setText("Cidade:");
        attCad.add(jLabel9);
        jLabel9.setBounds(23, 163, 40, 16);

        attCadBtn.setText("Atualizar");
        attCadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attCadBtnActionPerformed(evt);
            }
        });
        attCad.add(attCadBtn);
        attCadBtn.setBounds(166, 188, 76, 23);

        container.add(attCad, "card5");

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 430, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attIdVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attIdVarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attIdVarActionPerformed

    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        container.setVisible(true);
        attCad.setVisible(false);
        excCad.setVisible(false);
        buscaCad.setVisible(false);
        addCad.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        container.setVisible(true);
        addCad.setVisible(false);
        excCad.setVisible(false);
        buscaCad.setVisible(false);
        attCad.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        container.setVisible(true);
        addCad.setVisible(false);
        buscaCad.setVisible(false);
        attCad.setVisible(false);
        excCad.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        container.setVisible(true);
        addCad.setVisible(false);
        excCad.setVisible(false);
        attCad.setVisible(false);
        buscaCad.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void AddUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserBtnActionPerformed
        String nome1 = addNomeVar.getText();
        String idade1 = addIdadeVar.getText();
        String cidade1 = addCidVar.getText();
        
        Usuario n = new Usuario(nome1, idade1, cidade1);
        listaUsers.add(n);
        addLinhaNaTabela();
    }//GEN-LAST:event_AddUserBtnActionPerformed

    public void addLinhaNaTabela(){
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        ArrayList<Usuario> lista = listaUsers;
        Object linhaDado[] = new Object[4];
        for (int i = 0; i < lista.size(); i++) {
            linhaDado[0] = String.valueOf(i);
            linhaDado[1] = lista.get(i).nome;
            linhaDado[2] = lista.get(i).idade;
            linhaDado[3] = lista.get(i).cidade;
            
        }
        modelo.addRow(linhaDado);
    }
    
    private void attCadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attCadBtnActionPerformed
        // TODO add your handling code here:
        
        int id = Integer.parseInt(attIdVar.getText());
        String nome = attNomeVar.getText();
        String idade = attIdadeVar.getText();
        String cidade = attCidVar.getText();
        
        for(int j = 0; j < listaUsers.size(); j++){
            if (j == id) {
                listaUsers.get(j).setNome(nome);
                listaUsers.get(j).setIdade(idade);
                listaUsers.get(j).setCidade(cidade);
                
            }   
        }
    }//GEN-LAST:event_attCadBtnActionPerformed

    private void excExcluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excExcluirBtnActionPerformed
        // TODO add your handling code here
        String id = excCidVar.getText();
        String nome = excNomeVar.getText();
        String Idade = excIdadeVar.getText();
        String Cidade = excCidVar.getText();
        
        try {
            for (int i = 0; i < listaUsers.size(); i++){
                if (listaUsers.get(i).getCidade().equals(id)) {
                    listaUsers.remove(i);
                }            
            }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_excExcluirBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUserBtn;
    private javax.swing.JPanel addCad;
    private javax.swing.JTextField addCidVar;
    private javax.swing.JTextField addIdadeVar;
    private javax.swing.JTextField addNomeVar;
    private javax.swing.JPanel attCad;
    private javax.swing.JButton attCadBtn;
    private javax.swing.JTextField attCidVar;
    private javax.swing.JTextField attIdVar;
    private javax.swing.JTextField attIdadeVar;
    private javax.swing.JTextField attNomeVar;
    private javax.swing.JPanel buscaCad;
    private javax.swing.JPanel container;
    private javax.swing.JPanel excCad;
    private javax.swing.JTextField excCidVar;
    private javax.swing.JButton excExcluirBtn;
    private javax.swing.JTextField excIdVar;
    private javax.swing.JTextField excIdadeVar;
    private javax.swing.JTextField excNomeVar;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField12;
    // End of variables declaration//GEN-END:variables
}
